apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hi@upo.one
    privateKeySecretRef:
      name: letsencrypt-production
    dns01:
      providers:
      - name: route53
        route53:
          accessKeyID: AKIAJPSOWDBQ3TOH6GUA
          secretAccessKeySecretRef:
            name: route53-credentials
            key: secret-access-key
          region: eu-west-1