---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: redis-pv
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-volume
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: postgresql-pv
    fsType: ext4
