---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "adminer-config"
  namespace: "default"
  labels:
    app: "adminer"
data:
  ADMINER_DEFAULT_SERVER: "mysql"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "adminer"
  namespace: "default"
  labels:
    app: "adminer"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "adminer"
  template:
    metadata:
      labels:
        app: "adminer"
    spec:
      containers:
      - name: "adminer"
        image: "adminer"
        env:
        - name: "ADMINER_DEFAULT_SERVER"
          valueFrom:
            configMapKeyRef:
              key: "ADMINER_DEFAULT_SERVER"
              name: "adminer-config"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "adminer-hpa"
  namespace: "default"
  labels:
    app: "adminer"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "adminer"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

