apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: openfaas-crt
spec:
  secretName: openfaas-crt
  dnsNames:
    - prod.upodroid.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - prod.upodroid.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer