---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "adminer-config"
  namespace: "default"
  labels:
    app: "adminer"
data:
  ADMINER_DEFAULT_SERVER: "mysql"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "adminer"
  namespace: "default"
  labels:
    app: "adminer"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "adminer"
  template:
    metadata:
      labels:
        app: "adminer"
    spec:
      containers:
      - name: "adminer"
        image: "adminer"
        env:
        - name: "ADMINER_DEFAULT_SERVER"
          valueFrom:
            configMapKeyRef:
              key: "ADMINER_DEFAULT_SERVER"
              name: "adminer-config"
---