- name: Bootstrap Env
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_file: ~/ansible.json
    project: peerless-text-229510
    auth_kind: serviceaccount
    region: europe-west2
    network: dev

  tasks:

   - name: Allocate an IP Address
     gcp_compute_address:
      state: present
      name: 'maker'
      region: {{ region}}
      project: "{{ project }}"
      auth_kind: "{{ auth_kind }}"
      service_account_file: "{{ service_account_file }}"
      var: address

   - name: Make the network      
     gcp_compute_network:
      name: "dev"
      region: {{ region}}
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present

   - name: create a subnetwork
     gcp_compute_subnetwork:
       name: devnet-uk
       network: {{ network }}
       ip_cidr_range: 10.1.0.0/24
       region: {{ region}}
       project: {{ gcp_project }}
       auth_kind: {{ gcp_cred_kind }}
       service_account_file: {{ gcp_cred_file }}
       state: present

   - name: create a cluster
     gcp_container_cluster:
        name: maker
        network: {{ region }}
        initial_node_count: 3
        node_config:
          machine_type: n1-standard-2
          disk_size_gb: 50
          oauth_scopes:
           - https://www.googleapis.com/auth/compute
           - https://www.googleapis.com/auth/monitoring
           - https://www.googleapis.com/auth/logging.write
           - https://www.googleapis.com/auth/service.management.readonly
           - https://www.googleapis.com/auth/service.management.readonly
        zone: europe-west2-b
        project: {{ project }}
        auth_kind: {{ auth_kind }}
        service_account_file: {{ service_account_file }}
        state: present